### ISSUE TITLE
Actividad 4

### ISSUE THREAD

**Issue by mel-16** [SistemasTecTlaxiaco/actividad-4-diseno-de-objeto-3d-en-blender-team-lmn#1]
[Actividad 4.pdf](https://github.com/SistemasTecTlaxiaco/actividad-4-diseno-de-objeto-3d-en-blender-team-lmn/files/14655054/Actividad.4.pdf)

**Comment by josealfredo79** [comment]
calificacion..????

**Comment by Heidi-19** [comment]
Calificación: 20%

**Comment by josealfredo79** [comment]
Bien hecho y revisado..
